#!bin/bash
cd ~

# Vim installs
ln -s ~/dotfiles/.vimrc .vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/dotfiles/bundle/Vundle.vim
vim +PluginInstall +qall

# Install oh-my-zsh
sudo apt install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Dot files
mkdir .i3
ln -s ~/dotfiles/.i3config .i3/config
ln -s ~/dotfiles/.tmux.conf .tmux.conf
ln -s ~/dotfiles/.zshrc .zshrc
ln -s ~/dotfiles/.emacs .emacs
