#!bin/bash

# Vim installs
cd ~
touch .vimrc
echo "source ~/.vim/vimrc" >> .vimrc
open ~/.vim/Monaco-Powerline.otf
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Install oh-my-zsh
sudo apt install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Tmux
mv .vim/tmux.conf .tmux.conf
